### ISSUE TITLE
Unrecognized commend

### ISSUE THREAD

**Issue by Felinelx** [AlejandraArnedo/Wound-healing-size-tool#3]
![image](https://user-images.githubusercontent.com/80799213/111401423-445c1080-8697-11eb-86b7-0225103afa50.png)
Hello, I was wondering if anyone could help solve this issue: after installing and open my image/or when I run the macro, the codes would not run as described in the article and the error message occurs as "unrecognized command: "wound healing size tool options" in line 119"

**Comment by Felinelx** [comment]
Just figured out I did not installed that macro in the right folder. Thanks.
Quick note, is it possible to add some features such as looping through files of the same folder for this macro?

**Comment by AlejandraArnedo** [comment]
You can open all your images and select Images> Stacks> Images to stack. Then, just follow the tutorial for Wound_healing_size_tool (Stack analysis)

Hope it works

**Comment by Felinelx** [comment]
Thanks for replying.
Could you please offer me some suggestions on the variance window radius, threshold value, and percentage of saturated pixels to set for my picture (see attached)?
I am highly grateful for any help.

***@***.***D71AAA.D1D308F0]

Sincerely,
Xiao

**Comment by AlejandraArnedo** [comment]
Hi Xiao!

I don't see any attachment.

**Comment by Felinelx** [comment]
The picture was too large that I tried twice but could not send it.
Would you mind opening the link below to view it?
https://drive.google.com/file/d/1HRWkWtAjp2v8zncuX61PO_MU96cTEWof/view?usp=sharing

Thanks,
Xiao

**Comment by AlejandraArnedo** [comment]
You can use the next set of parameters:
![image](https://user-images.githubusercontent.com/62746075/111559395-cd8e4880-8766-11eb-98e6-856d80d192ed.png)

![image](https://user-images.githubusercontent.com/62746075/111559364-c0715980-8766-11eb-9dc8-860903d080d4.png)

**Comment by Felinelx** [comment]
This is amazing!
Thank you so much!

Kind regards,
Xiao

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
